# Generated by Django 4.0.4 on 2022-05-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='question_id',
            new_name='question',
        ),
    ]
