# Generated by Django 4.0.4 on 2022-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_answer_id_likeanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likequestion',
            name='is_like',
        ),
        migrations.AddField(
            model_name='likequestion',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
    ]
