# Generated by Django 4.0.4 on 2022-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
    ]
