# Generated by Django 4.0.4 on 2022-05-14 17:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_profile_id_answer_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='icons/no_name.png', upload_to=app.models.user_directory_path),
        ),
    ]
